---

- hosts: node
  roles:
    - { role: server, become: "{{ should_become  }}" }
    - { role: geerlingguy.pip, become: "{{ should_become }}" }
    - { role: geerlingguy.docker, become: "{{ should_become }}" }
    - node

  vars:
    docker_users:
      - node
    pip_install_packages:
      - name: docker
      - name: docker-compose

  vars_prompt:
    - name: "obada_testnet_version"
      prompt: "Which network version do you want to deploy?\n1- Testnet-1"
      private: no
      default: "1"
      

# Configure server
# Install and configure firewall
