---

- name: Add SSH public key.
  ansible.posix.authorized_key:
    user: node
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/obada_node_ssh_key.pub') }}"
  become: "{{ should_become }}"

- name: Configure Node.
  block:

    - name: Create Node folder.
      file:
        path: "/home/node/.cored/{{ item }}"
        state: directory
      with_items:
        - config
        - data

    - name: Copy config files.
      copy:
        src:  "{{ lookup('env','HOME') + '/testnets/testnet-' + obada_testnet_version  +  '/' + item }}"
        dest: "/home/node/.cored/config"
      with_items:
        - genesis.json

    - shell: id -u
      register: remote_uid

    - shell: id -g
      register: remote_gid

    - name: Setting remote uid and gid
      set_fact:
        uid: "{{ remote_uid.stdout }}"
        gid: "{{ remote_gid.stdout }}"

    - name: Copy docker-compose file.
      template:
        src: "docker-compose.yml.j2"
        dest: "/home/node/docker-compose.yml"
        mode: 0600

    - name: Running docker-compose.
      community.docker.docker_compose:
        project_src: "/home/node"
        recreate: always

    - name: Add persistent peers.
      replace: 
        path: /home/node/.cored/config/config.toml
        regexp: '(^persistent_peers\s=\s)(".*")$'
        # TODO: fetch IPs from DNS TXT record
        replace: '\1"4f31e487f02be47bb2dab0c49a97f90739e0e7f5@52.206.218.105:26656"'

    - name: Restart a Node.
      community.docker.docker_container:
        name: node
        state: started
        restart: yes

    - name: Catch Node status.
      community.docker.docker_container_exec:
        container: node
        command: /bin/sh -c "sleep 5 && ./fullcored status --home /home/obada/.cored"
      register: node_status

    - name: Print Node status.
      debug:
        msg: "The Node installation was completed. If you want your node to be included into persistent peers of the network, please send {{ (node_status.stdout | from_json).NodeInfo.id }}@{{ ansible_ssh_host }}:26656 to techops@obada.io"
      
  become_user: node
  become: yes
